/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package test.app
import com.hivemq.client.extensions.PriorityClass
import com.hivemq.client.extensions.TopicPriority
import com.hivemq.client.mqtt.datatypes.MqttQos
import com.hivemq.client.mqtt.datatypes.MqttTopicFilter
import com.hivemq.client.mqtt.mqtt5.Mqtt5Client
import java.util.*

fun main(args: Array<String>) {

    val client = Mqtt5Client.builder()
        .identifier(UUID.randomUUID().toString())
        .serverHost("165.22.126.152")
        .addTopicPriority(TopicPriority(MqttTopicFilter.of("routine/#"), PriorityClass.ROUTINE))
        .addTopicPriority(TopicPriority(MqttTopicFilter.of("priority/#"), PriorityClass.PRIORITY))
        .addTopicPriority(TopicPriority(MqttTopicFilter.of("immediate/#"), PriorityClass.IMMEDIATE))
        .addTopicPriority(TopicPriority(MqttTopicFilter.of("flash/#"), PriorityClass.FLASH))
        .buildBlocking()

    client.connect()
    client.publishWith().topic("testtopic/1").payload("Hei".toByteArray()).qos(MqttQos.AT_MOST_ONCE).send()

    client.publishWith().topic("nottesttopic/1").payload("Hei".toByteArray()).qos(MqttQos.AT_MOST_ONCE).send()
}
