deleted file mode 100644
index cc87e9c..0000000
--- a/client/src/main/java/com/hivemq/client/extensions/TopicPriority.java
+++ /dev/null
@@ -1,39 +0,0 @@
-/*
- * Copyright 2018-present HiveMQ and the HiveMQ Community
- *
- * Licensed under the Apache License, Version 2.0 (the "License");
- * you may not use this file except in compliance with the License.
- * You may obtain a copy of the License at
- *
- *     http://www.apache.org/licenses/LICENSE-2.0
- *
- * Unless required by applicable law or agreed to in writing, software
- * distributed under the License is distributed on an "AS IS" BASIS,
- * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
- * See the License for the specific language governing permissions and
- * limitations under the License.
- */
-
-package com.hivemq.client.extensions;
-
-import com.hivemq.client.mqtt.datatypes.MqttTopicFilter;
-import org.jetbrains.annotations.NotNull;
-
-public class TopicPriority {
-
-    private final @NotNull MqttTopicFilter filter;
-    private final @NotNull PriorityClass priority;
-
-    public TopicPriority(@NotNull MqttTopicFilter filter, @NotNull PriorityClass priority) {
-        this.filter = filter;
-        this.priority = priority;
-    }
-
-    public MqttTopicFilter getTopicFilter(){
-        return filter;
-    }
-
-    public PriorityClass getPriorityClass(){
-        return priority;
-    }
-}
