deleted file mode 100644
index fba9235..0000000
--- a/.github/workflows/broker.yml
+++ /dev/null
@@ -1,77 +0,0 @@
-name: Broker CI
-on:
-  pull_request:
-    branches: [ main ]
-  push: 
-    branches: [ main ]
-
-jobs:
-  check:
-    name: Check code for bugs and run tests
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: broker
-
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set up JDK 11
-      uses: actions/setup-java@v1
-      with:
-        java-version: 11
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
-    - name: Check tests and spot bugs
-      run: ./gradlew check
-  build:
-    name: Build the broker
-    runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: broker
-    steps:
-    - uses: actions/checkout@v2
-    - name: Set up JDK 11
-      uses: actions/setup-java@v1
-      with:
-        java-version: 11
-    - name: Grant execute permission for gradlew
-      run: chmod +x gradlew
-    - name: Build project
-      run: ./gradlew build
-  build-docker:
-    name: Build docker image
-    runs-on: ubuntu-latest
-    needs: [check, build]
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v1
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v1
-      - name: Login to DockerHub
-        uses: docker/login-action@v1 
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: Build and push
-        id: docker_build
-        uses: docker/build-push-action@v2
-        with:
-          context: broker
-          push: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
-          tags: tokongs/ffi02-broker:latest
-          file: broker/docker/Dockerfile
-  deploy:
-    name: Deploy docker image to server
-    runs-on: ubuntu-latest
-    needs: build-docker
-    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-    steps:
-      - name: Run deployment script on server via SSH
-        uses: garygrossgarten/github-action-ssh@release
-        with:
-          command: ./deploy.sh
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          privateKey: ${{ secrets.SSH_PRIVATE_KEY}}
