deleted file mode 100644
index fb54aec..0000000
--- a/test-app/src/main/kotlin/test/app/App.kt
+++ /dev/null
@@ -1,16 +0,0 @@
-/*
- * This Kotlin source file was generated by the Gradle 'init' task.
- */
-package test.app
-
-import com.github.ajalt.clikt.core.CliktCommand
-import com.github.ajalt.clikt.core.subcommands
-import test.app.commands.*
-
-class Cli : CliktCommand() {
-    override fun run() {
-    }
-}
-
-fun main(args: Array<String>) =
-    Cli().subcommands(Publish(), Subscribe(), Unsubscribe(), Synthetic(), Periodic(), Analyze()).main(args)
