deleted file mode 100644
index 596c3fc..0000000
--- a/broker/src/main/java/com/hivemq/extensions/priority/TopicPriority.java
+++ /dev/null
@@ -1,45 +0,0 @@
-/*
- * Copyright 2019-present HiveMQ GmbH
- *
- * Licensed under the Apache License, Version 2.0 (the "License");
- * you may not use this file except in compliance with the License.
- * You may obtain a copy of the License at
- *
- *     http://www.apache.org/licenses/LICENSE-2.0
- *
- * Unless required by applicable law or agreed to in writing, software
- * distributed under the License is distributed on an "AS IS" BASIS,
- * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
- * See the License for the specific language governing permissions and
- * limitations under the License.
- */
-
-package com.hivemq.extensions.priority;
-
-import com.hivemq.extension.sdk.api.annotations.NotNull;
-
-
-public class TopicPriority {
-
-    private final @NotNull String filter;
-    private final @NotNull PriorityClass priorityClass;
-    private final @NotNull int priority;
-
-    public TopicPriority(@NotNull String filter, @NotNull PriorityClass priorityClass, @NotNull int priority) {
-        this.filter = filter;
-        this.priorityClass = priorityClass;
-        this.priority = priority;
-    }
-
-    public String getTopicFilter(){
-        return filter;
-    }
-
-    public PriorityClass getPriorityClass(){
-        return priorityClass;
-    }
-
-    public int getPriority(){
-        return priority;
-    }
-}
\ No newline at end of file
