deleted file mode 100644
index 98107b6..0000000
--- a/Dockerfile.test-app
+++ /dev/null
@@ -1,18 +0,0 @@
-FROM gradle:6.7 as builder
-WORKDIR /tmp
-
-COPY gradle/ gradle/
-COPY gradlew .
-COPY settings.gradle.kts .
-COPY gradle.properties .
-COPY client/ client/
-COPY test-app/ test-app/
-
-
-RUN gradle test-app:installDist
-
-FROM openjdk:15-alpine
-WORKDIR /etc/test-app
-COPY --from=builder /tmp/test-app/build/install/test-app .
-
-ENTRYPOINT ["./bin/test-app"]
\ No newline at end of file
