deleted file mode 100644
index 5d0c866..0000000
--- a/test-app/build.gradle.kts
+++ /dev/null
@@ -1,45 +0,0 @@
-import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
-
-
-plugins {
-    id("org.jetbrains.kotlin.jvm") version "1.4.32"
-
-    application
-    distribution
-}
-
-repositories {
-    jcenter()
-}
-
-dependencies {
-    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))
-    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
-
-
-    implementation("com.github.ajalt.clikt:clikt:3.1.0")
-    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.3")
-    implementation(project(":client"))
-
-    testImplementation("org.jetbrains.kotlin:kotlin-test")
-    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")
-}
-
-application {
-    mainClass.set("test.app.AppKt")
-}
-
-
-tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
-    kotlinOptions {
-        jvmTarget = "11"
-    }
-}
-val compileKotlin: KotlinCompile by tasks
-compileKotlin.kotlinOptions {
-    jvmTarget = "1.8"
-}
-val compileTestKotlin: KotlinCompile by tasks
-compileTestKotlin.kotlinOptions {
-    jvmTarget = "1.8"
-}
\ No newline at end of file
