deleted file mode 100644
index 84e999a..0000000
--- a/broker/.github/ISSUE_TEMPLATE/config.yml
+++ /dev/null
@@ -1,5 +0,0 @@
-blank_issues_enabled: true
-contact_links:
-  - name: HiveMQ Community Forum
-    url: https://community.hivemq.com/
-    about: Please ask and answer questions here.
